In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Extraer información de la base de datos

In [53]:
raw_data = pd.read_excel('R_booooo\data\DATOS HISTÓRICOS 2023_2024_TODAS ESTACIONES_ITESM.xlsx')
raw_data.shape

(13872, 240)

In [54]:
raw_data.head()

,Unnamed: 0,SURESTE,SURESTE.1,SURESTE.2,SURESTE.3,SURESTE.4,SURESTE.5,SURESTE.6,SURESTE.7,SURESTE.8,...,NOROESTE 3.5,NOROESTE 3.6,NOROESTE 3.7,NOROESTE 3.8,NOROESTE 3.9,NOROESTE 3.10,NOROESTE 3.11,NOROESTE 3.12,NOROESTE 3.13,NOROESTE 3.14
0,NaN,CO,NO,NO2,NOX,O3,PM10,PM2.5,PRS,RAINF,...,PM10,PM2.5,PRS,RAINF,RH,SO2,SR,TOUT,WSR,WDR
1,date,ppm,ppb,ppb,ppb,ppb,ug/m3,ug/m3,mmhg,mm/hr,...,ug/m3,ug/m3,mmhg,mm/hr,%,ppb,KW/m2,degC,KMPH,DEG
2,2023-01-01 00:00:00,2.37,54.5,32.6,87.1,3,110,68,721.7,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-01-01 01:00:00,2.12,38.7,30.3,68.9,3,116,67.18,721.5,0,...,246,NaN,707.4,0,59,2.9,0,14.14,65.3,95
4,2023-01-01 02:00:00,2.05,38.7,28.8,67.4,3,117,75.12,721.1,0,...,239,NaN,707,0,59,3.2,0,14.11,60.9,90

In [55]:
raw_data.tail()

,Unnamed: 0,SURESTE,SURESTE.1,SURESTE.2,SURESTE.3,SURESTE.4,SURESTE.5,SURESTE.6,SURESTE.7,SURESTE.8,...,NOROESTE 3.5,NOROESTE 3.6,NOROESTE 3.7,NOROESTE 3.8,NOROESTE 3.9,NOROESTE 3.10,NOROESTE 3.11,NOROESTE 3.12,NOROESTE 3.13,NOROESTE 3.14
13867,2024-07-31 19:00:00,0.67,NaN,4.3,7.5,26,88,NaN,721.7,0,...,117,13.73,707.5,0,46,2.8,0.003,29.87,13.1,63
13868,2024-07-31 20:00:00,0.66,2.9,4.5,7.4,24,94,NaN,721.8,0,...,90,13.05,707.9,0,48,2.7,0,28.93,11.8,41
13869,2024-07-31 21:00:00,0.65,2.7,3.9,6.6,24,83,NaN,722.1,0,...,90,12.72,708.4,0,50,3,0,28.31,11.6,41
13870,2024-07-31 22:00:00,0.65,2.8,3.9,6.7,23,95,NaN,722.5,0,...,104,13.63,709.1,0,58,3,0,27.25,15.3,35
13871,2024-07-31 23:00:00,0.68,2.5,4.8,7.3,20,103,NaN,723.2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Limpieza, Tipo de Datos, Valores Faltantes

In [58]:
# Eliminar columnas vacias
raw_data.dropna(how='all', axis=1, inplace=True)
raw_data.shape

# Establecer nans y cambiar nombre de la primera columna
raw_data.replace("", np.nan, inplace=True)
raw_data.rename(columns={'Unnamed: 0': 'Date'}, inplace=True)

# Retirar primeras dos filas con metadatos
raw_data = raw_data.drop([0, 1])

# Resetear index
raw_data = raw_data.reset_index(drop=True)

# Hacer datetime columna Date
raw_data["Date"] = pd.to_datetime(raw_data["Date"])

# Hacer Columnas Numéricas
for col in raw_data.columns:
    if col != "Date":
        raw_data[col] = pd.to_numeric(raw_data[col], errors="coerce")

# Resetear el indice como la fecha
raw_data.set_index("Date", inplace=True)

# Revisar valores nulos
raw_data.isna().sum()

SURESTE           185
SURESTE.1         366
SURESTE.2         153
SURESTE.3         154
SURESTE.4         406
                 ...
NOROESTE 3.10    1363
NOROESTE 3.11     141
NOROESTE 3.12     116
NOROESTE 3.13    1966
NOROESTE 3.14     215
Length: 224, dtype: int64

In [59]:
raw_data.head()

,SURESTE,SURESTE.1,SURESTE.2,SURESTE.3,SURESTE.4,SURESTE.5,SURESTE.6,SURESTE.7,SURESTE.8,SURESTE.9,...,NOROESTE 3.5,NOROESTE 3.6,NOROESTE 3.7,NOROESTE 3.8,NOROESTE 3.9,NOROESTE 3.10,NOROESTE 3.11,NOROESTE 3.12,NOROESTE 3.13,NOROESTE 3.14
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-01 02:00:00,2.05,38.7,28.8,67.4,3.0,117.0,75.12,721.1,0.0,71.0,...,239.0,NaN,707.0,0.0,59.0,3.2,0.0,14.11,60.9,90.0
2023-01-01 03:00:00,2.50,60.5,29.1,89.4,3.0,135.0,82.81,720.8,0.0,68.0,...,275.0,NaN,706.8,0.0,59.0,2.3,0.0,14.08,58.1,84.0
2023-01-01 04:00:00,1.94,42.3,25.7,67.7,NaN,132.0,59.56,720.7,0.0,73.0,...,NaN,NaN,706.8,0.0,58.0,1.8,0.0,12.94,61.4,87.0
2023-01-01 05:00:00,1.35,10.2,23.1,33.2,NaN,96.0,33.58,720.7,0.0,71.0,...,103.0,NaN,706.8,0.0,58.0,1.8,0.0,12.83,62.9,88.0
2023-01-01 06:00:00,1.27,7.8,22.5,30.3,4.0,59.0,34.65,720.6,0.0,68.0,...,85.0,NaN,706.8,0.0,58.0,1.7,0.0,13.06,62.2,90.0

In [60]:
print(raw_data.shape)

(13868, 224)

In [61]:
# Primera interpolación de datos faltantes
data_interpolate = (
    raw_data
    .interpolate(method="time", limit=3, limit_direction="both", limit_area="inside")
)

data_interpolate.isna().sum()

SURESTE            49
SURESTE.1          26
SURESTE.2          26
SURESTE.3          26
SURESTE.4          57
                 ...
NOROESTE 3.10    1224
NOROESTE 3.11       9
NOROESTE 3.12       6
NOROESTE 3.13    1695
NOROESTE 3.14      39
Length: 224, dtype: int64

In [62]:
data_interpolate.head()

,SURESTE,SURESTE.1,SURESTE.2,SURESTE.3,SURESTE.4,SURESTE.5,SURESTE.6,SURESTE.7,SURESTE.8,SURESTE.9,...,NOROESTE 3.5,NOROESTE 3.6,NOROESTE 3.7,NOROESTE 3.8,NOROESTE 3.9,NOROESTE 3.10,NOROESTE 3.11,NOROESTE 3.12,NOROESTE 3.13,NOROESTE 3.14
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-01 02:00:00,2.05,38.7,28.8,67.4,3.000000,117.0,75.12,721.1,0.0,71.0,...,239.0,NaN,707.0,0.0,59.0,3.2,0.0,14.11,60.9,90.0
2023-01-01 03:00:00,2.50,60.5,29.1,89.4,3.000000,135.0,82.81,720.8,0.0,68.0,...,275.0,NaN,706.8,0.0,59.0,2.3,0.0,14.08,58.1,84.0
2023-01-01 04:00:00,1.94,42.3,25.7,67.7,3.333333,132.0,59.56,720.7,0.0,73.0,...,189.0,NaN,706.8,0.0,58.0,1.8,0.0,12.94,61.4,87.0
2023-01-01 05:00:00,1.35,10.2,23.1,33.2,3.666667,96.0,33.58,720.7,0.0,71.0,...,103.0,NaN,706.8,0.0,58.0,1.8,0.0,12.83,62.9,88.0
2023-01-01 06:00:00,1.27,7.8,22.5,30.3,4.000000,59.0,34.65,720.6,0.0,68.0,...,85.0,NaN,706.8,0.0,58.0,1.7,0.0,13.06,62.2,90.0